### ISSUE TITLE
Service boot loop

### ISSUE THREAD

**Issue by Polyterative** [klutchell/balena-adguard#1]
Trying to set it up using the code exactly as it is and it loops service boot and shutdown.

```
Killing service 'dns-cloudflare sha256:5057096bc63b3b8e5a6b1fb3947e03ae5ad9404d9e4c4fde9264209e437ff0ea'
25.07.19 13:31:26 (+0200) Service exited 'adguard sha256:08d44956b9e2e6eca6788945fddd73245c537ccd5d14f6799fe0eeac17f63aa5'
25.07.19 13:31:26 (+0200) Restarting service 'adguard sha256:08d44956b9e2e6eca6788945fddd73245c537ccd5d14f6799fe0eeac17f63aa5'
25.07.19 13:30:59 (+0200) <adguard> standard_init_linux.go:207: exec user process caused "exec format error"
25.07.19 13:31:08 (+0200) <adguard> standard_init_linux.go:207: exec user process caused "exec format error"
25.07.19 13:31:21 (+0200) <adguard> standard_init_linux.go:207: exec user process caused "exec format error"
25.07.19 13:31:30 (+0200) Service exited 'dns-cloudflare sha256:5057096bc63b3b8e5a6b1fb3947e03ae5ad9404d9e4c4fde9264209e437ff0ea'
25.07.19 13:31:35 (+0200) <adguard> standard_init_linux.go:207: exec user process caused "exec format error"
```

Rapsberry 3B+ 

Variables (extras from my last pihole push)

![image](https://user-images.githubusercontent.com/16295552/61871325-d589dc80-aee0-11e9-858f-743a6dc9f1f9.png)

**Comment by Polyterative** [comment]
Solved by changing line 10 in the `docker-compose` file
```
    image: adguard/adguardhome:armhf-v0.97.1
```

**Comment by brainstorm** [comment]
The certbot container/service requires a similar change (when deploying to an ARMv6 RaspberryPi 1):

```diff
$ git diff
diff --git a/certbot/Dockerfile b/certbot/Dockerfile
index e07f540..cffca0f 100644
--- a/certbot/Dockerfile
+++ b/certbot/Dockerfile
@@ -1,4 +1,4 @@
-FROM certbot/certbot:arm64v8-latest
+FROM certbot/certbot:arm32v6-latest

 COPY entrypoint.sh /

diff --git a/docker-compose.yml b/docker-compose.yml
index 8b5c431..ec94556 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -9,7 +9,7 @@ services:

     # https://hub.docker.com/r/adguard/adguardhome
     adguard:
-        image: adguard/adguardhome:arm64-v0.101.0
+        image: adguard/adguardhome:armhf-edge
         network_mode: host
         privileged: true
         volumes:
```

Balena should allow to have several different Dockerfiles which are built depending on the architecture, see "Multiple docker files" on https://www.balena.io/blog/running-a-desktop-manager-with-balena/ ... @klutchell would you include such a change here?

**Comment by Clementinox** [comment]
I'm on RPi 3 which is supported, but I will try the changes and let you know in an hour or two.
Thank you!

**Comment by Clementinox** [comment]
i get this while pushing code:

`[Error]             Could not detect project type: Service adguard: Could not find a Dockerfile for this service
[Error]             Not deploying release.
Remote build failed`

**Comment by klutchell** [comment]
If you're testing on RPi3 you need to be running the 64-bit host OS. I can add a 3rd Dockerfile to support 32-bit RPi3 and can see how it goes.

**Comment by Clementinox** [comment]
> If you're testing on RPi3 you need to be running the 64-bit host OS. I can add a 3rd Dockerfile to support 32-bit RPi3 and can see how it goes.
> 
> Can you try again with the latest from the `armv7hf` branch?

Will try now, I wonder if I accidentally installed Balena OS 32bit, thats why i am having issues.

**Comment by Clementinox** [comment]
i get the following, i think its just port issue? anyway i can change it through variables?

> `2020/04/04 19:29:10 [info] Stopped
2020/04/04 19:29:10 [fatal] listen tcp 0.0.0.0:3000: bind: address already in use
Service exited 'adguard sha256:0947d8ac069ae322e6b4b019d4181f421e40ec41329133a14ea3c44903c96abd'`

**Comment by klutchell** [comment]
You can change it in the docker-compose with a new command for adguard.

https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#command-line-arguments

```yaml
    adguard:
        build: ./adguard
        network_mode: host
        privileged: true
        command: --host 8080
        volumes:
            - 'adguardhome_work:/opt/adguardhome/work:rw'
            - 'adguardhome_conf:/opt/adguardhome/conf:rw'
            - 'letsencrypt:/etc/letsencrypt:ro'
```

But I find it unusual that 3000 would be in use by anything on the balena host. Unless you have duplicate containers running or something.

**Comment by Clementinox** [comment]
> You can change it in the docker-compose with a new command for adguard.
> 
> https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#command-line-arguments
> 
> ```yaml
>     adguard:
>         build: ./adguard
>         network_mode: host
>         privileged: true
>         command: --host 8080
>         volumes:
>             - 'adguardhome_work:/opt/adguardhome/work:rw'
>             - 'adguardhome_conf:/opt/adguardhome/conf:rw'
>             - 'letsencrypt:/etc/letsencrypt:ro'
> ```
> 
> But I find it unusual that 3000 would be in use by anything on the balena host. Unless you have duplicate containers running or something.

Seems to work just fine on the master branch.
I had balenaSound also running and after doing some searching I realized that currently only works on 32bit that's why my OS was 32bit and not working with your application. 
Sorry for the confusion. Thank you for the help!
