### ISSUE TITLE
Service Exit loop

### ISSUE THREAD

**Issue by Clementinox** [klutchell/balena-adguard#3]
HI I am trying to setup two projects on one unit as shown here:
https://www.balena.io/blog/two-projects-one-device-turn-your-raspberry-pi-into-a-multitool/#balenaSound-pihole

But i keep getting the following error:
sha256:82f7bfb64202be529c9a4b36c3be0ae32ca6cd7180a25ec7cfb4bf2b31ed67be'
 certbot  standard_init_linux.go:207: exec user process caused "exec format error"
 certbot  standard_init_linux.go:207: exec user process caused "exec format error"
 certbot  standard_init_linux.go:207: exec user process caused "exec format error"
Restarting service 'adguard sha256:219fa21da52af6f222166403205943e97e208b261687b8833da621d771e3f10f'
 adguard  standard_init_linux.go:207: exec user process caused "exec format error"
 adguard  standard_init_linux.go:207: exec user process caused "exec format error"
 adguard  standard_init_linux.go:207: exec user process caused "exec format error"

Any idea how to fix this? I tried using different port numbers instead of 80:80
I used 3000:80, still nothing

I am trying to run balena sound and balena adguard together.

Thank you,

**Comment by brainstorm** [comment]
The hardware you have does not support the binary architecture you are trying to run (exec format error).

Example: Raspberry pi with ARM32 trying to run/load an ARM64 binary.
